### ISSUE TITLE
Catch errors during blockchain height request

### ISSUE THREAD

**Issue by GenericStudent** [ardevd/bobcatpy#11]
Currently the Helium API is down, this is causing the blockchain height lookup to fail.

The result is all [summary keys after height](https://github.com/ardevd/bobcatpy/blob/main/bobcatpy.py#L73) aren't set (such as temps, ips etc).

We should catch the request error (check the [response of height](https://github.com/ardevd/bobcatpy/blob/main/bobcatpy.py#L91) for None before attempting double dict index access.

Hopefully this resolves the API having a negative impact if its down / responding badly.

Cheers

**Comment by ardevd** [comment]
Totally agree. Good point! Thanks! I'll take care of it ;)
