### ISSUE TITLE
GET requests to miner occasionally hang

### ISSUE THREAD

**Issue by cversek** [ardevd/bobcatpy#5]
The background is that I am using this library within a script that repeatedly probes the sync status of the miner over a long time period (hours/days).  I found that the sync_status requests would hang the process on rare occasions (but frequently enough to be annoying).

**Comment by ardevd** [comment]
Thanks for reporting and fixing this issue.

**Comment by cversek** [comment]
No problem, this is a very helpful package for me right now.

If you would like to help, I have a mysterious issue with my new Bobcat 300
miner that I'm trying to work around: every several hours it stops syncing
and the gap just keeps growing without intervention.  If I get it to
reboot, it will often load a snapshot right away without me needing to
"fast sync" it (this seems like new undocumented behavior?), then it will
usually be able to close the gap and mine for a few hours.  I'm working on
a script to baby-sit the miner and force reboot it when the gap starts to
grow past some cutoff.

If you know some way to diagnose and potentially fix the problem that would
be awesome.  Still, I think a continual monitoring script (with data persistence)
may be useful to others, so I'd like to release the code when it's a little
more mature.
